name: Set up skopeo environment
author: warjiang
description: |-
  Downloads, installs, and configures skopeo environment.
  Adds the `skopeo` CLI command to the $PATH.

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'terminal'
  color: 'blue'

# Define your inputs here.
# inputs:
#   milliseconds:
#     description: 'Your input description here'
#     required: true
#     default: '1000'

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
